{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubemend.labels" . | nindent 4 }}
{{- end }}
