apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/kubemend/gitops.git
    targetRevision: main
    path: apps/shop-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
